#!/usr/bin/with-contenv bash

exec s6-setuidgid abc /usr/bin/smokeping --master-url=https://smokeping.voxo.co/smokeping/smokeping.cgi --shared-secret=/config/slave_secret --cache-dir=/data/cache/ --nodaemon

