#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/var/cache/smokeping \
	/data/cache

# copy config files


[[ ! -e "/config/slave_secret" ]] && echo "dobel" > /config/slave_secret

PREV_DIR=$(pwd)

	cd /defaults/smoke-conf || exit
	shopt -s globstar nullglob
	for i in *
 	do
	[[ ! -e "/config/${i}" ]] && cp -v "${i}" "/config/${i}"
	done

cd "${PREV_DIR}" || exit




# permissions
chmod 400 /config/slave_secret
chown -R abc:abc \
	/config \
	/data \
	/var/cache/smokeping 

